name: update docs on server

on:
  pull_request:
    types: [closed]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  update-docs:
    name: Updating The Docs
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-22.04

    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@v1.2.2

        with:
            host: 89.117.36.52
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            passphrase: ${{ secrets.SSH_PASSPHRASE }}
            script: ${{ secrets.REMOTE_DEPLOY_SCRIPT_PATH }}